version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: notification_db
    restart: always
    environment:
      POSTGRES_DB: neondb
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: npg_iZbfa7k8Bdvt
    ports:
      - "5433:5433"
